package parselog

import (
	"bufio"
	"fmt"
	"os"
	"strconv"

	cmdargs "github.com/m/v2/cmd-args"
)

type GameData struct {
	GameName   string
	TotalKills int64
	Kills      map[string]int //	mapping from player to associated kills
	Players    map[string]bool
}

type KillData struct {
	GameName string
	Kills    map[string]int //	mapping from weapon to associated kills
}

// function to parse logs generated by Quake game using file-name provided in fileInfo object
func ParseLogs(fileInfo cmdargs.FileInfo) {

	//	opening file to read logs from
	content, err := os.Open(fileInfo.LogFile)
	if err != nil {
		fmt.Printf("Unable to read log file: %s", err)
		os.Exit(1)
	}

	//	create scanner object to read file line by line
	scanner := bufio.NewScanner(content)

	gameNumber := 0

	var gameInfo GameData
	var killInfo KillData
	//	read file till EOF
	for scanner.Scan() {
		//	read string from log file
		line := scanner.Text()

		//	check if new game is initialized by checking key word "InitGame" substring at 7:15
		if line[7:15] == "InitGame" {
			gameNumber++
			//	read info of a particular game
			gameInfo, killInfo = ReadGameInfo(scanner, "game_"+strconv.FormatInt(int64(gameNumber), 10))
			fmt.Println(gameInfo.GameName)
			fmt.Println(killInfo.GameName)
		}
	}
}
